name: lfpy
dependencies:
  - python=3.7
  - pip
  - mpich
  - gcc_linux-64
  - pthread-stubs
  - mpi4py
  - sphinx=2.4.1
  - sphinx_rtd_theme=0.4.3
  - numpydoc=0.9.2
  - pip:
      - numpy
      - Cython
      - numpydoc
